{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "green-kube.serviceAccountName" . }}
  labels:
    {{- include "green-kube.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Name}}-reader
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", 'create', "update", "delete"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name}}-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "green-kube.serviceAccountName" .}}
    namespace: {{.Release.Namespace}}
roleRef:
    kind: ClusterRole
    name: {{.Release.Name}}-reader
    apiGroup: rbac.authorization.k8s.io