{{- if .Values.enableVictim }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-victim
  labels:
    app: memory-waster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-waster
  template:
    metadata:
      labels:
        app: memory-waster
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "64Mi"
{{- end}}